In [1]:
import sys
import warnings
import numpy as np
import pandas as pd
from skmultilearn.adapt import MLkNN
from sklearn.metrics import hamming_loss, accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')

In [2]:
# read data from csv
df = pd.read_csv('C:\\Users\\Pallavi PC\\Documents\\project1\\data\\essays.csv', names=['author_id', 'essay', 'Extraversion', 'Neuroticism',
                                      'Agreeableness', 'Conscientiousness', 'Openness'], encoding='ansi')


In [7]:
df

author_id                                              essay  \
0             #AUTHID                                               TEXT   
1     1997_504851.txt  Well, right now I just woke up from a mid-day ...   
2     1997_605191.txt  Well, here we go with the stream of consciousn...   
3     1997_687252.txt  An open keyboard and buttons to push. The thin...   
4     1997_568848.txt  I can't believe it!  It's really happening!  M...   
...               ...                                                ...   
2463     2004_493.txt       I'm home. wanted to go to bed but remembe...   
2464     2004_494.txt       Stream of consiousnesssskdj. How do you s...   
2465     2004_497.txt  It is Wednesday, December 8th and a lot has be...   
2466     2004_498.txt  Man this week has been hellish. Anyways, now i...   
2467     2004_499.txt  I have just gotten off the phone with brady. I...   

     Extraversion Neuroticism Agreeableness Conscientiousness Openness  
0            cEXT        cNEU          cAGR              cCON     cOPN  
1               n           y             y                 n        y  
2               n           n             y                 n        n  
3               n           y             n                 y        y  
4               y           n             y                 y        n  
...           ...         ...           ...               ...      ...  
2463            n           y             n                 y        n  
2464            y           y             n                 n        y  
2465            n           n             y                 n        n  
2466            n           y             n                 n        y  
2467            n           y             y                 n        y  

[2468 rows x 7 columns]

In [8]:
X = df['essay']
X

0                                                    TEXT
1       Well, right now I just woke up from a mid-day ...
2       Well, here we go with the stream of consciousn...
3       An open keyboard and buttons to push. The thin...
4       I can't believe it!  It's really happening!  M...
                              ...                        
2463         I'm home. wanted to go to bed but remembe...
2464         Stream of consiousnesssskdj. How do you s...
2465    It is Wednesday, December 8th and a lot has be...
2466    Man this week has been hellish. Anyways, now i...
2467    I have just gotten off the phone with brady. I...
Name: essay, Length: 2468, dtype: object

In [30]:
y = np.asarray(df[df.columns[2:]])
y = np.where(y == 'n', 0, 1)
y

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1],
       [0, 0, 1, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1]])

In [31]:
X.shape

(2468,)

In [32]:
y.shape

(2468, 5)

In [33]:
# initializing TfidfVectorizer 
vetorizar = TfidfVectorizer(max_features=3000, max_df=0.85)
# fitting the tf-idf on the given data
vetorizar.fit(X)
  
# splitting the data to training and testing data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
  
# transforming the data
X_train_tfidf = vetorizar.transform(X_train)
X_test_tfidf = vetorizar.transform(X_test)

In [55]:
# using Multi-label kNN classifier
mlknn_classifier = MLkNN()
mlknn_classifier.fit(X_train, y_train)

ValueError: could not convert string to float: "I can't stand how removed the users are from the control of the system. With internet explorer I can't even get it to work with trumpet Winsock, so if I want to use IE then I have to go down to the computer center and pay them a bunch of money for the UT connect system when I already have trumpet Winsock that has always worked fine in the past. now with Netscape I keep having a completely different problem, there are several times that I go to web pages that I know are there and they aren't for example I tried to go to the pretesting WebPages and I soon as I sent my social security number out over the web, which I'm not especially happy about having to do, it tells me that the document has no data. The same thing has happened before when I try to log on to the Columbia house website. I consider myself a pretty smart person, but I cannot figure out at all what the hell is going on with this stupid then. I know I have to go down to campus and use a computer down there for 45 minutes to do the pretesting. and why the hell is it when you connect to UT and go on the web the connecting is so freaking slow. I swear UT must have some really outdated equipment down there because my download speeds never get over 1 K. that's ridiculous. but this is the way at UT. When you go to a school with 50000 students everything takes a little longer and your chances of having to deal with an idiot are raised considerably. I think I have an especially low tolerance for stupid people. Uneducated is different but there seem to be a lot of people out that that are truly student I think, and they frustrate the hell out of me. It's not that I'm a genius of something, but there are some real idiots out there. There is this girl in my engineering economics class that sits up in the front and will ask questions that make no freaking sense at all. How in the hell does someone get to be an upper division engineering major and be so stupid. obviously it happens through, although most of the really stupid people that I have to deal with come from working at Wal-Mart. I guess that's my own fault, it's not like I should expect anything else. When I was a CSM we would have some cashiers that I have not idea at all how they got hired. I think personnel hires anyone with a pulse sometimes, I mean if the person sitting across the table from you just has this completely blank look on their face, that's a good sign that you shouldn't hire them. Another thing that bugs me are all the stupid laws regarding alcohol in this country. I mean either it should be legal or it should, but alcohol seems to be the only think that is legal to some of the adults and only part of the time. I mean were are talking about adults, some of them may not be especially bright but they still are adults. if 18 is good enough for every thing else then it should be good enough for alcohol. you can get married, go to jail, go to war, own property, get a gun, hell anything that any other adult does except drink. seems pretty backwards to me. something else that is freaking stupid and at the very least unfair is the way that car insurance companies can completely screw over guys. when a girl turns 21 she gets a good rate, but a guy has to wait until he is 25, hello but most of the really awful drivers that I have ever been around are women, they are  the ones that pay no attention at all to what is going on around them. but since older people control the laws etceteras the younger people are going to continue to get screwed over, I think they should make people over 60 pay the same rates as 18 year olds, that would be funny. oh well out of time, it's been real "

In [37]:
vectorizer = TfidfVectorizer()
xx_train = vectorizer.fit_transform(X_train)
xx_test = vectorizer.transform(X_test)

In [49]:
classifier = MLPClassifier(activation='tanh', alpha=0.0001, hidden_layer_sizes=(60),
                               learning_rate='adaptive', max_iter=20, solver='lbfgs')
classifier.fit(xx_train, y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=60,
              learning_rate='adaptive', max_iter=20, solver='lbfgs')

In [51]:
predictions = classifier.predict(xx_test)
print("Confusion Matrix:")
print(classification_report(y_test, predictions))
score = accuracy_score(y_test, predictions)
print("Accuracy:", score)

Confusion Matrix:
              precision    recall  f1-score   support

           0       0.60      0.57      0.58       402
           1       0.59      0.61      0.60       360
           2       0.55      0.51      0.52       386
           3       0.62      0.46      0.53       408
           4       0.63      0.54      0.58       393

   micro avg       0.59      0.53      0.56      1949
   macro avg       0.59      0.54      0.56      1949
weighted avg       0.60      0.53      0.56      1949
 samples avg       0.57      0.53      0.51      1949

Accuracy: 0.04993252361673414


In [52]:
new_sentences = ["I can't believe it!  It's really happening!  My pulse is racing like mad. So this is what it's like. now I finally know what it feels like. just a few more steps. I wonder if he is going to get any sleep tonight!?  I sure won't!  Well, of course I have a million deadlines to meet tomorrow so I'll be up late anyway. But OH! I'm so so excited!  Yes!  Yes!  I can't believe it is finally happening. Wait! Calm down. We aren't officially a couple yet. What if I end up not liking him?  That would be horrible. Oh great, I wonder how long it'll take me to finish those Calculus problems?  I'll get it done. Don't you always, Amy?  I can't believe Bob did it!  He really did it!  He is THE miracle worker. If things turn out all right I will owe him more than I can ever repay. I wonder what Steve is doing in Malaysia right now?  An entire month!  I'll likely clean out his refrigerator by then. Omigosh!  Food, lunch tomorrow, what will I ever say to him?  He is perfect in every way imaginable. It is so important for him to think of me the same way. well, maybe not Perfect, but certainly dynamic. Who would have ever thought!  Good things do indeed come to those who wait!  Oh, I'll have to remember to sign the poster he made tomorrow morning. I hope Steve's alarm clock is reliable and I don't oversleep. That would be tragic if I slept 'til noon and missed the lunch. Thank goodness Portia is coming along. I will definitely need her support as well as Bob's. just having her there will take away some of the tension and put me more at ease. I'll have to rehearse what I say beforehand. things can only get better from here, right? hopefully. oh, I'm so nervous!  He will be too. maybe even more so. it'll be ok. Why in the world do humans put themselves through such torture. maybe love is really worth it?"]
new_sentence_tfidf = vectorizer.transform(new_sentences)
  
predicted_sentences = classifier.predict(new_sentence_tfidf)
print(predicted_sentences)

[[0 0 1 0 1]]


In [53]:
predicted = classifier.predict(xx_test)
predicted

array([[1, 0, 1, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 0, 0],
       ...,
       [1, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0]])

In [54]:
print(accuracy_score(y_test, predicted))
print(hamming_loss(y_test, predicted))

0.04993252361673414
0.43724696356275305
